### ISSUE TITLE
Unable to compile TypeScript

### ISSUE THREAD

**Issue by rahulrkr08** [strongloop/loopback-next-example#67]
###Overview

I am getting below error after `npm start`. Can anyone please help me on this ?

#####Error

```
rahuls-air:loopback-next-example rahulradhakrishnan$ npm start

> loopback-next-example@1.0.0 start /Users/rahulradhakrishnan/Documents/projects/myprojects/loopback-next-example
> bin/start

All microservices stopped successfully.
Starting microservices...
Started Account microservice, PID: 57533
Started Customer microservice, PID: 57534
Started Transaction microservice, PID: 57535
Started Facade microservice, PID: 57537
All microservices started successfully.
To test the application, run "npm test".
rahuls-air:loopback-next-example rahulradhakrishnan$ 
/Users/rahulradhakrishnan/Documents/projects/myprojects/loopback-next-example/node_modules/ts-node/src/index.ts:296
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
index.ts (1,23): Module '"/Users/rahulradhakrishnan/Documents/projects/myprojects/loopback-next-example/services/transaction/node_modules/loopback-next/packages/core/index"' has no exported member 'Server'. (2305)
    at getOutput (/Users/rahulradhakrishnan/Documents/projects/myprojects/loopback-next-example/node_modules/ts-node/src/index.ts:296:15)
    at /Users/rahulradhakrishnan/Documents/projects/myprojects/loopback-next-example/node_modules/ts-node/src/index.ts:325:16
    at Object.compile (/Users/rahulradhakrishnan/Documents/projects/myprojects/loopback-next-example/node_modules/ts-node/src/index.ts:479:11)
    at Module.m._compile (/Users/rahulradhakrishnan/Documents/projects/myprojects/loopback-next-example/node_modules/ts-node/src/index.ts:379:43)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/rahulradhakrishnan/Documents/projects/myprojects/loopback-next-example/node_modules/ts-node/src/index.ts:382:12)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)

/Users/rahulradhakrishnan/Documents/projects/myprojects/loopback-next-example/node_modules/ts-node/src/index.ts:296
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
```

**Comment by virkt25** [comment]
@rahulrkr08 Have a look at the master branch now and follow the updated instructions to get it to work.
